apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-gtiq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0028-tenant/tkrw-pr712-0075-0028-app/devfile-sample-gtiq@sha256:794903d1dc03528eb8231a75cb38dc91415d0f4e4ff7331391b0f17c585e3816
        name: my-nodejs
        resources: {}
status: {}
